// <auto-generated />
using System;
using AthleteMcpServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AthleteMcpServer.Migrations
{
    [DbContext(typeof(AthleteDbContext))]
    [Migration("20260504103136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AthleteMcpServer.Domain.Activities.CompletedRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageCadence")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("AveragePacePerKm")
                        .HasColumnType("interval");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<decimal?>("ElevationGainMeters")
                        .HasColumnType("numeric");

                    b.Property<string>("ExternalActivityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("MovingTime")
                        .HasColumnType("interval");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PlannedSessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RatePerceivedExertion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShoeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("PlannedSessionId");

                    b.HasIndex("ShoeId");

                    b.ToTable("CompletedRuns");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Athletes.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentWeeklyDistanceKm")
                        .HasColumnType("numeric");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("PreferredLongRunDay")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredUnits")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<decimal>("TypicalLongRunDistanceKm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Coaching.CoachDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("CoachDecisions");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Equipment.Shoe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("DistanceLoggedKm")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("FirstUsedOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("RetireAfterKm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Shoes");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Goals.TrainingGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<double?>("TargetTime")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("TrainingGoals");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Health.ReadinessEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AffectedRunning")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("RequiresFollowUp")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("ReadinessEntries");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.TrainingPlans.PlannedSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompletedRunId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TargetDistanceKm")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan?>("TargetDuration")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("TargetPacePerKm")
                        .HasColumnType("interval");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("PlannedSessions");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.TrainingPlans.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TargetWeeklyDistanceKm")
                        .HasColumnType("numeric");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("GoalId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Activities.CompletedRun", b =>
                {
                    b.HasOne("AthleteMcpServer.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AthleteMcpServer.Domain.TrainingPlans.PlannedSession", null)
                        .WithMany()
                        .HasForeignKey("PlannedSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AthleteMcpServer.Domain.Equipment.Shoe", null)
                        .WithMany()
                        .HasForeignKey("ShoeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Coaching.CoachDecision", b =>
                {
                    b.HasOne("AthleteMcpServer.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Equipment.Shoe", b =>
                {
                    b.HasOne("AthleteMcpServer.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Goals.TrainingGoal", b =>
                {
                    b.HasOne("AthleteMcpServer.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.Health.ReadinessEntry", b =>
                {
                    b.HasOne("AthleteMcpServer.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.TrainingPlans.PlannedSession", b =>
                {
                    b.HasOne("AthleteMcpServer.Domain.TrainingPlans.TrainingPlan", null)
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.TrainingPlans.TrainingPlan", b =>
                {
                    b.HasOne("AthleteMcpServer.Domain.Athletes.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AthleteMcpServer.Domain.Goals.TrainingGoal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AthleteMcpServer.Domain.TrainingPlans.TrainingPlan", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
